### ISSUE TITLE
hawq_rm_nvseg_perquery_perseg_limit clarification

### ISSUE THREAD

**Issue by dimon777** [pivotalguru/TPC-DS#12]
This is not an issue but a question:
hawq_rm_nvseg_perquery_perseg_limit parameter what is the guideline to set this parameter? I have read documentation on it but don't fully understand implications. For example if I have 40 CPU datanode should I set this parameter to a much higher value than default 6, say 12, 24, 32?

**Comment by RunningJon** [comment]
I think you should ask this on the HAWQ Dev Email List.
