### ISSUE TITLE
Generate data step hangs

### ISSUE THREAD

**Issue by voxkat** [pivotalguru/TPC-DS#16]
I seem to be experiencing the same issue described in issue #8.  The generate data steps seems to hang, and the same .dat files listed in that issue are empty for me as well.  I have confirmed connectivity to all the nodes using gpssh-exkeys, and I'm not able to follow what exactly the fix to the issue was by @dimon777.  Is there any guidance or additional info available?

**Comment by RunningJon** [comment]
Some zero byte files are expected and required.  Here is the code that uses "touch" to create those files.
https://github.com/pivotalguru/TPC-DS/blob/master/01_gen_data/generate_data.sh#L34

Check the generate_data.$CHILD.log file on each segment host.  It may give you an error message.  This is the step that does it:
https://github.com/pivotalguru/TPC-DS/blob/master/01_gen_data/rollout.sh#L87

Lastly, you can check to see if dsdgen is still running on the segment hosts.  A quick way to do that is with gpssh.
gpssh -f segment_hosts.txt -e "ps -ef | grep dsdgen | grep -v grep | wc -l"

**Comment by voxkat** [comment]
Thanks for your quick reply.  The generate_data.$CHILD.log files all simply show the full path of the .dat files, no errors.   And all dsdgen processes have finished as well, none returned with ps -ef.

Here are the processes left running as it "hangs"... note that this is a single-node environment with 6 segments:

[gpadmin@greenplum ~]$ ps -ef |grep tpc
root     100193 100170  0 18:05 pts/0    00:00:00 /bin/bash ./tpcds.sh
root     100288 100193  0 18:05 pts/0    00:00:00 su --session-command=cd "/pivotalguru/TPC-DS"; ./rollout.sh 5 false tpcds false 1 false false true true true true true true true 1 gpadmin
gpadmin  100289 100288  0 18:05 pts/0    00:00:00 bash -c cd "/pivotalguru/TPC-DS"; ./rollout.sh 5 false tpcds false 1 false false true true true true true true true 1
gpadmin  100290 100289  0 18:05 pts/0    00:00:00 /bin/bash ./rollout.sh 5 false tpcds false 1 false false true true true true true true true 1
gpadmin  100394 100290  0 18:05 pts/0    00:00:00 /bin/bash /pivotalguru/TPC-DS/01_gen_data/rollout.sh 5 false tpcds false 1 1
gpadmin  105994 101157  0 18:16 pts/1    00:00:00 grep --color=auto tpc
[gpadmin@greenplum ~]$

**Comment by RunningJon** [comment]
If you don't see any dsdgen processes, then it is hanging where it does a while loop and checks every 5 seconds to see if there are any dsdgen processes running.

https://github.com/pivotalguru/TPC-DS/blob/master/01_gen_data/rollout.sh#L130

It is calling this function:
https://github.com/pivotalguru/TPC-DS/blob/master/01_gen_data/rollout.sh#L22

Can you run this where $i is the hostname of the single node?
ssh -o ConnectTimeout=0 -n -f $i "bash -c 'ps -ef | grep generate_data.sh | grep -v grep | wc -l'"

I suspect you are having an issue with this command not working correctly.  BTW, are you using CentOS/Redhat 6 or 7?

**Comment by RunningJon** [comment]
And try that command as gpadmin, not root.

**Comment by voxkat** [comment]
Yes, I was looking at exactly that line of code and that is the issue.  It connects successfully via ssh and returns "0" as expected, but hangs and does not return to a prompt.  This is a RHEL 7 implementation.

Any thoughts on a fix?

**Comment by RunningJon** [comment]
Do you see anything in /var/log/secure or /var/log/messages?  Something is preventing the login at this point.
What do you have in /etc/ssh/sshd_config?  

Do you have firewalls turned off?  

Do you have all of the CentOS7 settings in place?
http://gpdb.docs.pivotal.io/520/install_guide/prep_os_install_gpdb.html

**Comment by voxkat** [comment]
Looks like replacing -f option with -t works fine:

`ssh -o ConnectTimeout=0 -n -t $i "bash -c 'ps -ef | grep generate_data.sh | grep -v grep | wc -l'"`

Can you advise where this edit needs to occur in the parent script/code?  It appears the 01_gen_data/rollout.sh script gets overwritten when tpcds.sh is launched.

**Comment by RunningJon** [comment]
The -f option is used to launch generate_data.sh as well as many other places in the code.  In the load step for instance, it uses -f.  It doesn't make sense that -f doesn't work at this step because it worked to generate the data.

The tpcds.sh script automatically pulls from github on every run.  To prevent that, you can edit tpcds.sh and comment out "repo_init".

I would check your /var/log/messages and /var/log/secure to see why it isn't working properly.

**Comment by voxkat** [comment]
I tried executing with replacing the '-f' option with '-t' for the ssh within get_count_generate_data() and it still hung (even though it did return a prompt when testing the ssh command manually).  So to your point, it is likely a different issue.

However /var/log/messages and secure output seem clean:
`[root@greenplum log]# tail messages
Feb  7 20:46:22 greenplum-5-dev systemd-logind: New session 8120 of user gpadmin.
Feb  7 20:46:22 greenplum-5-dev systemd: Started Session 8120 of user gpadmin.
Feb  7 20:46:22 greenplum-5-dev systemd: Starting Session 8120 of user gpadmin.
Feb  7 20:46:22 greenplum-5-dev systemd-logind: Removed session 8120.`

`[root@greenplum log]# tail secure
Feb  7 20:46:37 greenplum-5-dev sshd[43965]: pam_unix(sshd:session): session opened for user gpadmin by (uid=0)
Feb  7 20:46:37 greenplum-5-dev sshd[43967]: Received disconnect from xxx.xx.xx.xx port 52802:11: disconnected by user
Feb  7 20:46:37 greenplum-5-dev sshd[43967]: Disconnected from xxx.xx.xx.xx port 52802
Feb  7 20:46:37 greenplum-5-dev sshd[43965]: pam_unix(sshd:session): session closed for user gpadmin`


I will try to re-validate the system config, but have not encountered any ssh/access issues to this point.

**Comment by RunningJon** [comment]
I tried changing the scripts to use "-t" instead of "-f" and it hung so that isn't a workable solution.  There must be something missing in your config.

**Comment by voxkat** [comment]
To get past the issue, I just eliminated using ssh for that line/step since this implementation is only single-node, and the remainder of the process completed successfully.  I will investigate a different approach for multi-node cluster, or continue to identify any config issue.  Thanks for your help, this automation will be very helpful to TPC testing.

**Comment by amitj1jan** [comment]
Hi Jon,
I am facing the same issue on same line no in /01_gen_data/rollout.sh(L22), m running on RHEL7.
However as I am running in multi cluster node setup, can not use the work around used by @voxkat .
Also I have checked the OS recommended configs and all seem to be in place.
What do you suggest.

**Comment by RunningJon** [comment]
Do you see any dsdgen processes running on the segment hosts?

**Comment by amitj1jan** [comment]
No, and I see the data is generated and no change further happening in data directory.I am doing it only for 10G.
However, I got it overcome by doing this on /01_gen_data/rollout.sh
        sleep 3m
        for i in $(cat $PWD/../segment_hosts.txt); do
                #next_count=$(ssh -o ConnectTimeout=0 -n -f $i "bash -c 'ps -ef | grep generate_data.sh | grep -v grep | wc -l'" 2>&1 || true)
                sleep 5
                next_count="0"

And commenting out #repo_init and #script_check in tpcds.sh so that it doesn't pull the scripts from repo.
Thanks, for your quick response.
