### ISSUE TITLE
relation "pg_filespace_entry" does not exist

### ISSUE THREAD

**Issue by rz1970** [pivotalguru/TPC-DS#17]
Greenplum version: PostgreSQL 9.4beta1 (Greenplum Database 6.0.0-alpha.0 build dev-oss) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.3.1 20170216 (Red Hat 6.3.1-3), 64-bit compiled on Nov 12 2018 03:35:52

this issue happened both in tpc-h and tpc-ds

**Comment by RunningJon** [comment]
I have not done any testing with 6 yet so it isn't supported.  Is there an rpm yet for it?

**Comment by rz1970** [comment]
ok. thanks. 
I just saw the followings in the README.txt
"Supported versions:
Greenplum 4.3, 5.*, 6.*
Open Source Greenplum 5.*, 6.*
Beta: PostgreSQL 10.*
"
I use open source gpdb from GitHub: https://github.com/greenplum-db/gpdb, and I compile it according to the readme.

**Comment by RunningJon** [comment]
I made some changes that should resolve the problem.  Please give it another try.

**Comment by RunningJon** [comment]
Also try TPC-H.  I fixed those scripts too.

**Comment by rz1970** [comment]
Cool. Both TPC-DS and TPC-H work fine.

**Comment by orangeops** [comment]
I have this question too ！ 

“Relation "pg_filespace_entry" does not exist (diskusage)”

**Comment by RunningJon** [comment]
> I have this question too ！
> 
> “Relation "pg_filespace_entry" does not exist (diskusage)”

What version are you using?
