### ISSUE TITLE
Changes in Postgresql.conf causing to Stop Greenplum

### ISSUE THREAD

**Issue by amitj1jan** [pivotalguru/TPC-DS#18]
Have run this test successfully on Greenplum 5.16, however on Greenplum 4.3, because of bug, it is causing Greenplum startup failure, with below message:
2019-04-04 07:23:51.931038 GMT,,,p28056,th845141952,,,,0,,,seg-1,,,,,"FATAL","22023","ORCA is not supported by this build",,,,,,,,"assign_optimizer","guc_gp.c",5957,

On checking found that script(02_init/rollout.sh), inserts multiple records in postgresql.conf.
And below inserted line, causes Greenplum startup failure:
optimizer=on

This is done through below code:
/pivotalguru/TPC-DS/02_init/rollout.sh(L47)
psql -v ON_ERROR_STOP=1 -q -t -A -c "show optimizer" | grep -i "on" | wc -l; exit ${PIPESTATUS[0

**Comment by RunningJon** [comment]
What is the full version number of your 4.3 database?

**Comment by amitj1jan** [comment]
This is what I see from gpstate:
local Greenplum Version: 'postgres (Greenplum Database) 4.3.99.00 build dev'

Thanks,
Amit.

**Comment by RunningJon** [comment]
The latest 4.3.x release is 4.3.32 which has the optimizer GUC.
https://gpdb.docs.pivotal.io/43320/admin_guide/topics/g-pivotal-query-optimizer-parameters.html

This GUC was added to 4.3.12 in February 2017 so I believe the version you are on is older than 4.3.12 and isn't a supported version.  

Can you upgrade to a newer release of 4.3?

**Comment by amitj1jan** [comment]
Hi Jon,
As per https://github.com/pivotalguru/TPC-DS, GP 4.3 is supported.
Also I am looking at Greenplum upgrade(5.*)  or options as HAWQ. But before I do that, I want to benchmark the existing cluster(4.3.99), so upgrade to another 4.3* will not solve the purpose.

Though I was able to overcome reported error, it gets stuck in other issues:
libapr-1.so.0 related erro, could not start gpfdist
psql:/pivotalguru/TPC-DS/04_load/018.gpdb.inventory.sql:1: ERROR:  quicklz compression not supported (quicklz_compression.c:26)

Can I not use the older version of TPC-DS for the purpose, if yes can you suggest which one I should be using.

**Comment by RunningJon** [comment]
Quicklz is not included in the open source build but to my knowledge, 4.3 was never available in open source.  So, I did not know where you got this build.  

Your new problem of quicklz not supported suggests your catalog is not correct.  Do you have quicklz listed in pg_compression?
Reference:
https://github.com/pivotalguru/TPC-DS/blob/master/functions.sh#L54
