### ISSUE TITLE
Canceling query because of high VMEM usage.

### ISSUE THREAD

**Issue by whirlys** [pivotalguru/TPC-DS#19]
Hi.
I met Error during the test of TPC-DS and can't continue now:
```
ERROR:  Canceling query because of high VMEM usage. Used: 4613MB, available 507MB, red zone: 4608MB (runaway_cleaner.c:189)  (seg19 slice5 192.168.65.11:6007 pid=55634) (cdbdisp.c:254)
```
I tried to modify a lot of parameters but still have no effect, e.g:
- gp_vmem_protect_limit：5120
- shared_buffers：128MB
- work_mem：32MB
- maintenance_work_mem：64MB
- effective_cache_size：512MB

I set gp_vmem_protect_limit to 8192, 12288, 15360 by gpconfig but still not work.

### Env
- greenplum version: 5.1.8
- operating system: CentOS Linux release 7.3.1611 (Core)

There are 3 nodes in my Greenplum cluster.
- node6: 256G mem, 12 * 3.7T disk
- node7: 256G mem, 12 * 3.7T disk
- node11: 128G mem, 12 * 3.7T disk

```
[gpadmin@node6 TPC-DS]$ df -h
Filesystem           Size  Used Avail Use% Mounted on
/dev/mapper/cl-root   50G  7.3G   43G  15% /
devtmpfs             126G     0  126G   0% /dev
tmpfs                126G     0  126G   0% /dev/shm
tmpfs                126G  9.4M  126G   1% /run
tmpfs                126G     0  126G   0% /sys/fs/cgroup
/dev/sdc1           1014M  140M  875M  14% /boot
/dev/sdd             3.7T  307G  3.4T   9% /data/data9
/dev/sdl1            3.7T  307G  3.4T   9% /data/data6
/dev/sdj             3.7T  307G  3.4T   9% /data/data11
/dev/sdg1            3.7T  308G  3.4T   9% /data/data2
/dev/sdk1            3.7T  307G  3.4T   9% /data/data5
/dev/sdf             3.7T  307G  3.4T   9% /data/data10
/dev/sdi1            3.7T  307G  3.4T   9% /data/data4
/dev/sdm             3.7T  306G  3.4T   9% /data/data12
/dev/sdb             3.7T  307G  3.4T   9% /data/data8
/dev/sde1            3.7T  2.1T  1.6T  58% /data/data1
/dev/sda             3.7T  307G  3.4T   9% /data/data7
/dev/sdh1            3.7T  307G  3.4T   9% /data/data3
/dev/mapper/cl-home  392G   29G  364G   8% /home
tmpfs                 26G     0   26G   0% /run/user/0
tmpfs                 26G     0   26G   0% /run/user/1000
```

```
node6:
              total        used        free      shared  buff/cache   available
Mem:           251G        2.0G        243G        5.3G        5.5G        243G
Swap:          4.0G          0B        4.0G

node7:
              total        used        free      shared  buff/cache   available
Mem:           251G        2.0G        243G        5.3G        5.5G        243G
Swap:          2.2G          0B        2.2G

node11:
              total        used        free      shared  buff/cache   available
Mem:           125G        1.3G        118G        5.1G        5.3G        118G
Swap:          2.2G          0B        2.2G
```

tpcds_variables.sh
```
REPO="TPC-DS"
REPO_URL="https://github.com/pivotalguru/TPC-DS"
ADMIN_USER="gpadmin"
INSTALL_DIR="/pivotalguru"
EXPLAIN_ANALYZE="false"
RANDOM_DISTRIBUTION="false"
MULTI_USER_COUNT="5"
GEN_DATA_SCALE="1024"
SINGLE_USER_ITERATIONS="1"
RUN_COMPILE_TPCDS="false"
RUN_GEN_DATA="true"
RUN_INIT="true"
RUN_DDL="true"
RUN_LOAD="true"
RUN_SQL="true"
RUN_SINGLE_USER_REPORT="true"
RUN_MULTI_USER="true"
RUN_MULTI_USER_REPORT="true"
RUN_SCORE="true"
```

### Error log
tail tpcds.log
```
20190802:18:49:05:011726 analyzedb:node6:gpadmin-[INFO]:-Done.
/pivotalguru/TPC-DS/05_sql/rollout.sh
source ~/.bashrc

psql -v ON_ERROR_STOP=1 -A -q -t -P pager=off -v EXPLAIN_ANALYZE="" -f /pivotalguru/TPC-DS/05_sql/101.tpcds.01.sql | wc -l
psql -v ON_ERROR_STOP=1 -A -q -t -P pager=off -v EXPLAIN_ANALYZE="" -f /pivotalguru/TPC-DS/05_sql/102.tpcds.02.sql | wc -l
psql:/pivotalguru/TPC-DS/05_sql/102.tpcds.02.sql:59: ERROR:  Canceling query because of high VMEM usage. Used: 4610MB, available 510MB, red zone: 4608MB (runaway_cleaner.c:189)  (seg32 slice2 192.168.65.7:6008 pid=24111) (cdbdisp.c:254)
```
note:
the 59th line of 102.tpcds.02.sql is :
```
order by d_week_seq1;
```

### Observation
I observed memory changes during **execute 05_sql/102.tpcds.02.sql separately** in psql, here are three stage: 
1. In the beginning, the free memory of all nodes drops at approximately 1G.
   - node6: 239G -> 120G
   - node7:  239G -> 120G
   - node11: 111G -> 320M
2. When node11 drops to 320M, it starts to stay the same, and the other two nodes continue to decline
   - node6: 120G -> 90G
   - node7: 120G -> 90G
   - node11: keep at 320M 
3. node11 occurs Error
   - if set gp_vmem_protect_limit to 8192, 12288, its error message like this:
```
ERROR:  Canceling query because of high VMEM usage. Used: 4613MB, available 507MB, red zone: 4608MB (runaway_cleaner.c:189)  (seg19 slice5 192.168.65.11:6007 pid=55634) (cdbdisp.c:254)
```
   - if  set gp_vmem_protect_limit to 15360, its error message is "out of memory, cannot allocat ....8192...":

### please help
I also tried to modify the resource queue parameters, GEN_DATA_SCALE, but still can not be completed.

What is the difference between data overflowing into the spill file and data in vmem? When will it overflow and when will it be cancelled?

I don't know how to finish the TPC-DS test. please help. :simple_smile:

**Comment by RunningJon** [comment]
You stated that you are using 5.1.8 but that version doesn't exist.  Are you using 5.18? 

If you are, there is a known bug in Greenplum 5.18 with ANALYZE that causes this issue.  The root statistics are not gathered on partitioned tables so the optimizer generates terrible plans.  

Either downgrade to 5.17 or upgrade to the latest version which is 5.21.1 right now.

**Comment by whirlys** [comment]
@pivotalguru Thank you very much.  :smile: 

The current version is indeed 5.18, I will upgrade it to 5.21.
I closed the issue.
