### ISSUE TITLE
execute tpcds.sh error

### ISSUE THREAD

**Issue by qq363960630** [pivotalguru/TPC-DS#2]
executing on kslave2 ./start_gpfdist.sh 9001 /data/hawq/segment/pivotalguru_1
Started gpfdist on port 9001
executing on kslave2 ./start_gpfdist.sh 9002 /data/hawq/segment/pivotalguru_2
Started gpfdist on port 9002
executing on kslave2 ./start_gpfdist.sh 9003 /data/hawq/segment/pivotalguru_3
Started gpfdist on port 9003
executing on kslave2 ./start_gpfdist.sh 9004 /data/hawq/segment/pivotalguru_4
Started gpfdist on port 9004
executing on kslave2 ./start_gpfdist.sh 9005 /data/hawq/segment/pivotalguru_5
Started gpfdist on port 9005
executing on kslave2 ./start_gpfdist.sh 9006 /data/hawq/segment/pivotalguru_6
Started gpfdist on port 9006
executing on kslave1 ./start_gpfdist.sh 9001 /data/hawq/segment/pivotalguru_1
Started gpfdist on port 9001
executing on kslave1 ./start_gpfdist.sh 9002 /data/hawq/segment/pivotalguru_2
Started gpfdist on port 9002
executing on kslave1 ./start_gpfdist.sh 9003 /data/hawq/segment/pivotalguru_3
Started gpfdist on port 9003
executing on kslave1 ./start_gpfdist.sh 9004 /data/hawq/segment/pivotalguru_4
Started gpfdist on port 9004
executing on kslave1 ./start_gpfdist.sh 9005 /data/hawq/segment/pivotalguru_5
Started gpfdist on port 9005
executing on kslave1 ./start_gpfdist.sh 9006 /data/hawq/segment/pivotalguru_6
Started gpfdist on port 9006
psql -v ON_ERROR_STOP=ON -f /pivotalguru/TPC-DS/04_load/051.insert.call_center.sql | grep INSERT | awk -F ' ' '{print $3}'
psql:/pivotalguru/TPC-DS/04_load/051.insert.call_center.sql:1: ERROR:  External scan error: There are more external files (URLs) than primary segments that can read them (COptTasks.cpp:1756)

**Comment by RunningJon** [comment]
I can't reproduce this error.  Can you share your hawq-site.xml file?
