### ISSUE TITLE
ERROR:  could not open file "../log/rollout_gen_data.log" for reading: No such file or directory

### ISSUE THREAD

**Issue by parametriq** [pivotalguru/TPC-DS#20]
Whatever we did to surpass this problem gave no results so far. Help needed...

This week we've been trying to get some scoring on our **Greenplum 6.4.0** test cluster, faced a few challenges with memory and disk space, that was expected... but this is the error that stopped any further progress:

```
psql -v ON_ERROR_STOP=1 -a -f /pivotalguru/TPC-DS/06_single_user_reports/07.copy.gen_data.sql -v LOGFILE="'/pivotalguru/TPC-DS/06_single_user_reports/../log/rollout_gen_data.log'"
COPY tpcds_reports.gen_data FROM :LOGFILE WITH DELIMITER '|';
psql:/pivotalguru/TPC-DS/06_single_user_reports/07.copy.gen_data.sql:1: ERROR:  could not open file "/pivotalguru/TPC-DS/06_single_user_reports/../log/**rollout_gen_data.log**" for reading: No such file or directory
```

I tried all sorts of options in tpcds_variables.sh, but it seems that apart from EXPLAIN_ANALYZE logging any other logs don't work as expected. If this is based on where Greenplum stores its own log files -- that changed quite a bit from version 5.x to 6.x

Has anyone ever confirmed this to work with 6.x or this is specific to our environment? Greenplum OSS was deployed with go-gpdb installer. To provide expected env variables I had to create greenplum_path.sh and source it in .bashrc for tpcds.sh to start correctly (go-gpdb originally creates a different env file and sources it in /etc/profile.d/gpdb.profile.sh)

My greenplum_path.sh:

```
export GPHOME=/usr/local/greenplum-db-6.4.0
export PYTHONPATH=$GPHOME/lib/python
export PYTHONHOME=$GPHOME/ext/python
export PATH=$GPHOME/bin:$PYTHONHOME/bin:$PATH
export LD_LIBRARY_PATH=$GPHOME/lib:$PYTHONHOME/lib:$LD_LIBRARY_PATH
export OPENSSL_CONF=$GPHOME/etc/openssl.cnf
export MASTER_DATA_DIRECTORY=/data/master/gp_6.4.0_20200320124955-1
export PGPORT=3002
export PGDATABASE=gpadmin
export singleOrMulti=multi
```

**Comment by RunningJon** [comment]
This benchmark works with GP6.

Does this file exist?
/pivotalguru/TPC-DS/06_single_user_reports/../log/rollout_gen_data.log

What operating system version are you using?

**Comment by parametriq** [comment]
```
cat /etc/redhat-release
CentOS Linux release 7.7.1908 (Core)
```
no, this file (rollout_gen_data.log) is not created
...and after debugging today I'm starting to suspect that somehow "printf >> logfile" doesn't work in functions.sh at the end of log() function. It just quietly does not execute. Sounds crazy, I know

**Comment by RunningJon** [comment]
Does this output "foo bar"?
`printf "foo bar\n"`

**Comment by parametriq** [comment]
Surely it does.
I even tried to create some stripped down bash construct similar to your code, consisting of a few .sh files in different dirs starting each other. And inside were only PWD variables(BASH_SOURCE[0] magic), printf statements outputting some debug info and one simple function in a func.sh sourced within each of those little bash-scripts using "$PWD/func.sh", "$PWD/../func.sh", etc. The function in its turn "logged" a couple of messages to a file for me with `printf "sometext\n" >> somefile`.  It mimics all the parts of your code I thought could potentially cause trouble on my system and yet it works like a charm!

I started execution with "sudo nohup ... &", gave same permissions to files, kept similar directory structure to make sure everything is exactly the same. It works as it should.

I'm still missing something... rollout_* logs are not created for some another reason.

**Comment by RunningJon** [comment]
Try becoming root.  The easiest way is:

sudo bash
nohup ./tpcds.sh > tpcds.log 2>&1 < tpcds.log &


Or you can use this command to become root:

sudo su - 
nohup ./tpcds.sh > tpcds.log 2>&1 < tpcds.log &


Don't forget to add the "-" after "su".

**Comment by parametriq** [comment]
The first thing I checked was file permissions and user privileges, so we had already tried that last week. "Sudo bash" -- exactly this way...
Unfortunately it makes no difference. I wish it was that easy.

**Comment by RunningJon** [comment]
What timezone are you in?  I can host a zoom meeting to debug this issue if you like.

**Comment by parametriq** [comment]
Well, I think I found something finally!
Your function is simply named `log()` and called `log` in the rollout.sh scripts.
But typing `log` in the terminal on this particular system outputs this:
`...`
Yeah, that's right, three dots )

Now let's look at this portion of the tpcds.log:
```
139.tpcds.39.sql
myfilename: /pivotalguru/TPC-DS/01_gen_data/../05_sql/139.tpcds.39.sql
pos: 28
COMPLETE: dsqgen scale 1
...
/pivotalguru/TPC-DS/02_init/rollout.sh
check optimizer
check analyze_root_partition
check gp_autostats_mode
```

See those three dots? That's exactly where it calls log() function but instead bumps into that "log" thing from the shell.

And this is the root of all my problems:
```
# type log
log is a function
log ()
{
    printf "%s...\n" "$*"
}
```
A function for adding "..." at the end of anything. Extremely useful

Those CentOS's were deployed from cloud template images... who could've guessed they contain such interesting modification

**Comment by RunningJon** [comment]
Sounds like an easy fix for you then.  Do you need anything else before I close this issue?

**Comment by parametriq** [comment]
No, let's consider this resolved. Many thanks for your willingness to help!
