### ISSUE TITLE
Can not execute tpcds.sh in offline environments

### ISSUE THREAD

**Issue by CC-Hsu** [pivotalguru/TPC-DS#21]
Hi,

We try to execute TPC-DS tests in offline GPDB clusters but I stuck at external network check GitHub access check.

I guess it's caused by `script_check()` in [tpcds.sh script](https://github.com/pivotalguru/TPC-DS/blob/master/tpcds.sh).

It would be great if someone can improve TPC-DS scripts to make it workable to run in offline environments smoothly.

Thanks.

**Comment by RunningJon** [comment]
You can execute it offline. You have to download the repo first.

**Comment by CC-Hsu** [comment]
Hi,

I downloaded the latest script from GitHub webpage.

And I find a way to make it works in offline environment.
1) Rename extracted directory name to TPC-DS (originally it is TPC-DS_master).
2) Comment out `repo_init` from [`tpcds.sh`](https://github.com/pivotalguru/TPC-DS/blob/master/tpcds.sh)

I think it is OK now.

Thanks.
