### ISSUE TITLE
Setting RUN_COMPILE_TPCDS="false" does not disable compiling

### ISSUE THREAD

**Issue by CC-Hsu** [pivotalguru/TPC-DS#22]
Hi,

I find that setting `RUN_COMPILE_TPCDS=false` does not disable compiling.

I guess that [`00_compile_tpcds/rollout.sh`](https://github.com/pivotalguru/TPC-DS/blob/master/00_compile_tpcds/rollout.sh) does not check the variable.

This is a bit inconvenient and hope this can be improved.

Thanks.

**Comment by RunningJon** [comment]
Setting any of the RUN_* steps to false means the step will be skipped only if it has run successfully before. If you haven't compiled TPC-DS, then it will run this step regardless if you say to skip it or not. 

RUN_GEN_DATA is a great example of this. It is set to false so the first time you run the test, it generates the data. If you run the test again, the test sees that it has already generated the data and skips this step.  If you were to set RUN_GEN_DATA to true, it will delete any previously generated data and generate the data again.

**Comment by CC-Hsu** [comment]
Hi,

Thanks a lot for your explanation.
