### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by MURH17** [pivotalguru/TPC-DS#24]
请问为什么会执行脚本的时候要求输出密码呢？
grammar_support.o keywords.o list.o nulls.o permute.o print.o QgenMain.o query_handler.o r_params.o scaling.o StringBuffer.o substitution.o tdefs.o text.o tokenizer.o w_inventory.o y.tab.o release.o scd.o build_support.o parallel.o  -lm
gcc -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DYYDEBUG  -DLINUX -g -Wall   -c -o checksum.o checksum.c
gcc -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DYYDEBUG  -DLINUX -g -Wall  -o checksum checksum.o -lm
Password:
gsql: FATAL:  Invalid username/password,login denied.

**Comment by RunningJon** [comment]
I believe you don't have your Greenplum cluster initialized correctly. The gpadmin account doesn't appear to have passwordless ssh setup to the nodes in the cluster which is a requirement for Greenplum and TPC-DS.

**Comment by MURH17** [comment]
> I believe you don't have your Greenplum cluster initialized correctly. The gpadmin account doesn't appear to have passwordless ssh setup to the nodes in the cluster which is a requirement for Greenplum and TPC-DS.


In a newly installed cluster environment, there is only one omm user. There is no password to enter the omm user through the root user, but I don't know why this happens?

**Comment by MURH17** [comment]
![image](https://user-images.githubusercontent.com/77497821/129994798-c59eb90a-ef62-4285-b348-866a1fe8aee2.png)
发现有的时候可以正常退出，有的时候就会出现这样的问题，与执行脚本时报错一样
![image](https://user-images.githubusercontent.com/77497821/129994880-d7913dc9-0ba6-4de8-bede-bc0b03eec14b.png)

**Comment by MURH17** [comment]
![image](https://user-images.githubusercontent.com/77497821/129995278-f89ec9b9-0af6-46de-8d94-66a56950901e.png)

发现有的时候可以正常退出，有的时候就会出现这样的问题，与执行脚本时报错一样
![image](https://user-images.githubusercontent.com/77497821/129995289-a830951c-ee78-4e6b-bb92-b5dc7cc0720f.png)

**Comment by RunningJon** [comment]
Try editing the `tpcds_variables.sh` file and change the admin user from gpadmin to omm. 

You should also know that you may run into other problems using Greenplum when you are using a non-standard user to run the database.

**Comment by RunningJon** [comment]
You should review the other variables too. The default is 3TB which is pretty large for most systems.

**Comment by MURH17** [comment]
> Try editing the `tpcds_variables.sh` file and change the admin user from gpadmin to omm.
> 
> You should also know that you may run into other problems using Greenplum when you are using a non-standard user to run the database.

Hello, I really appreciate your help. You reminded me that I have solved the problem now, thank you! I wish you a happy life! Best wishes!
