### ISSUE TITLE
Should 02_init/rollout.sh set search path for ADMIN_USER?

### ISSUE THREAD

**Issue by funcode** [pivotalguru/TPC-DS#26]
It is running "ALTER USER $USER SET search_path=...", but I think it should be "ALTER USER $ADMIN_USER SET search_path..." as in fact the script is run by ADMIN_USER via "su -l $ADMIN_USER". This will cause that no queries got run when ADMIN_USER is not the login user.

**Comment by RunningJon** [comment]
But that doesn't impact the ability for the script to successfully execute the test.

**Comment by funcode** [comment]
It does when I set ADMIN_USER to "gpadmin" but I ran the script from another user's login shell.

**Comment by RunningJon** [comment]
The script is run as root and it then switches to the ADMIN_USER. At this point, the $USER variable is the ADMIN_USER.
