### ISSUE TITLE
execute on 04_load error

### ISSUE THREAD

**Issue by wubiaoi** [pivotalguru/TPC-DS#3]
tpcds.log is :

```
psql -v ON_ERROR_STOP=ON -f /data0/servers/tpcds/TPC-DS/04_load/051.insert.call_center.sql | grep INSERT | awk -F ' ' '{print $3}'
psql:/data0/servers/tpcds/TPC-DS/04_load/051.insert.call_center.sql:1: ERROR:  Could not allocate enough memory! bucket number of result hash table and external table should match each other (cdbdatalocality.c:4225)
```

hawq-site.xml:

``` xml

        <property>
                <name>hawq_rm_nvseg_perquery_limit</name>
                <value>512</value>
        </property>

        <property>
                <name>hawq_rm_nvseg_perquery_perseg_limit</name>
                <value>6</value>
        </property>

```

Thank you

**Comment by RunningJon** [comment]
"ERROR:  Could not allocate enough memory!" is an error raised from HAWQ because you don't have memory configured correctly.  Please refer to this documentation link: http://hdb.docs.pivotal.io/20/requirements/system-requirements.html

**Comment by amitj1jan** [comment]
Hi Hellopower,
Can u please tell what issue it was and how you fixed it.
As I am also getting the exactly same issue.

Thanks,
Amit.

**Comment by RunningJon** [comment]
You don't have enough resources allocated to HAWQ.  If you want to provide your configuration details, I can help.
