### ISSUE TITLE
Session report not avaialbe

### ISSUE THREAD

**Issue by dimon777** [pivotalguru/TPC-DS#9]
I've run a very small test (just to confirm everything works). I see this in the terminal output (99 rows):

```
SET
Timing is on.
query_id        session_1       session_2       session_3       session_4       session_5       session_6       session_7       session_8     session_9        session_10
01      1.1033  1.1025  1.1017  1.1031  0.965   0       0       0       0       0
02      47.47847        16.16351        3.3238  3.3301  3.3333  0       0       0       0       0
03      0.859   1.147   1.1487  1.1455  1.1648  0       0       0       0       0
04      4.4209  7.7177  7.7695  5.5675  6.6685  0       0       0       0       0
05      3.3159  3.3548  3.3931  3.33    3.3234  0       0       0       0       0
06      1.1655  1.1672  1.1722  1.1707  1.1647  0       0       0       0       0
...
...
98      0.736   0.763   0.733   0.722   0.772   0       0       0       0       0
99      2.2103  2.2241  2.2124  2.2235  2.2242  0       0       0       0       0
(99 rows)
Time: 9.187 ms
```

Is this query execution time in seconds for each session? Is there a way to obtain this report in the log directory? I can't find this report in there.

**Comment by RunningJon** [comment]
That is the multi-user report and the times are in seconds.  

You can send the output from STDOUT to a log file which is recommended in the README or you can run the reports manually from 06_single_user_reports and 08_multi_user_reports directories.

**Comment by RunningJon** [comment]
And the output of that report tells me you don't have all of the data directories listed as temp directories in HAWQ.  You should have a HAWQ temp directory per data disk.

**Comment by dimon777** [comment]
I understand having temp directories on each drive is not mandatory, but I agree it makes a lot of sense. Closing now...

**Comment by dimon777** [comment]
With regards to having a temp directory on each HDFS disk, how HAWQ handles loss of a drive in this case?

**Comment by RunningJon** [comment]
The last time I checked that, the segment would fail.  At that point, you
would need to revise the temp directories on that segment and then restart
the segment.  Or you could replace the bad drive.

**Comment by dimon777** [comment]
Thanks
